name: Exportar datos públicos

on:
  push:
    branches: [main]
    paths:
      - 'darts.db'
  workflow_dispatch:

jobs:
  export:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Exportar datos
        run: python export_public_data.py

      - name: Commit y push si hubo cambios
        run: |
          if [[ -n "$(git status --porcelain data)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data
            git commit -m "chore: actualizar datos públicos"
            git push
          else
            echo "No hay cambios en data/"
          fi
